# Generated by Django 3.1.7 on 2021-04-04 12:25

import functools

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to=images.models.user_directory_path, verbose_name='image')),
                ('result_image', models.ImageField(unique=True, upload_to=functools.partial(images.models.user_directory_path, *(), **{'unique': True}), verbose_name='result image')),
                ('random_from', models.SmallIntegerField(default=-100, help_text='Value from -255 to 255', validators=[django.core.validators.MinValueValidator(-255), django.core.validators.MaxValueValidator(255)])),
                ('random_to', models.SmallIntegerField(default=100, help_text='Value from -255 to 255', validators=[django.core.validators.MinValueValidator(-255), django.core.validators.MaxValueValidator(255)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
