# Generated by Django 3.1.7 on 2021-04-03 17:23

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210403_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='result_image',
            field=models.ImageField(blank=True, unique=True, upload_to=images.models.user_directory_path, verbose_name='result image'),
        ),
    ]
