# Generated by Django 3.1.7 on 2021-04-03 17:26

from django.db import migrations, models
import functools
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210403_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='result_image',
            field=models.ImageField(blank=True, upload_to=functools.partial(images.models.user_directory_path, *(), **{'unique': True}), verbose_name='result image'),
        ),
    ]
