# Generated by Django 3.1.7 on 2021-04-03 17:28

from django.db import migrations, models
import functools
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210403_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to=images.models.user_directory_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='result_image',
            field=models.ImageField(unique=True, upload_to=functools.partial(images.models.user_directory_path, *(), **{'unique': True}), verbose_name='result image'),
        ),
    ]
